-- CreateTable
CREATE TABLE "frutas" (
    "id" SERIAL NOT NULL,
    "nombre" TEXT NOT NULL,
    "nombre_cientifico" TEXT NOT NULL,
    "familia_botanica" TEXT,
    "otros_nombres" TEXT[],
    "descripcion" TEXT NOT NULL,
    "categoria" TEXT NOT NULL,
    "sabor" TEXT,
    "origen_pais" TEXT,
    "origen_region" TEXT,
    "temporada" TEXT[],
    "colores" TEXT[],
    "usos_culinarios" TEXT[],
    "beneficios" TEXT[],
    "alergias" TEXT[],
    "curiosidades" TEXT[],
    "imagenes" TEXT[],
    "porcion_g" INTEGER NOT NULL DEFAULT 100,
    "calorias_kcal" DOUBLE PRECISION,
    "carbohidratos_g" DOUBLE PRECISION,
    "azucares_g" DOUBLE PRECISION,
    "fibra_g" DOUBLE PRECISION,
    "proteinas_g" DOUBLE PRECISION,
    "grasas_g" DOUBLE PRECISION,
    "vitamina_c_mg" DOUBLE PRECISION,
    "vitamina_a_ug" DOUBLE PRECISION,
    "vitamina_k_ug" DOUBLE PRECISION,
    "potasio_mg" DOUBLE PRECISION,
    "calcio_mg" DOUBLE PRECISION,
    "hierro_mg" DOUBLE PRECISION,
    "conservacion_metodo" TEXT,
    "conservacion_duracion_dias" INTEGER,
    "creado_en" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "actualizado_en" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "frutas_pkey" PRIMARY KEY ("id")
);
