import swaggerJsdoc from "swagger-jsdoc";

const options: swaggerJsdoc.Options = {
  definition: {
    openapi: "3.0.0",
    info: {
      title: "Frutopedia API",
      version: "1.0.0",
      description: "API CRUD para frutas con filtros, paginación y validación",
    },
    servers: [{ url: "http://localhost:3000" }],
    components: {
      schemas: {
        Fruta: {
          type: "object",
          properties: {
            id: { type: "integer", example: 1 },
            nombre: { type: "string", example: "Manzana" },
            nombreCientifico: { type: "string", example: "Malus domestica" },
            familiaBotanica: { type: "string", example: "Rosaceae" },
            otrosNombres: { type: "array", items: { type: "string" } },
            descripcion: { type: "string" },
            categoria: { type: "string", example: "Pomácea" },
            sabor: { type: "string", example: "Dulce con notas ácidas" },
            origenPais: { type: "string" },
            origenRegion: { type: "string" },
            temporada: { type: "array", items: { type: "string" } },
            colores: { type: "array", items: { type: "string" } },
            usosCulinarios: { type: "array", items: { type: "string" } },
            beneficios: { type: "array", items: { type: "string" } },
            alergias: { type: "array", items: { type: "string" } },
            curiosidades: { type: "array", items: { type: "string" } },
            imagenes: { type: "array", items: { type: "string" } },
            porcionG: { type: "integer", example: 100 },
            caloriasKcal: { type: "number", example: 52 },
            carbohidratosG: { type: "number", example: 13.8 },
            azucaresG: { type: "number", example: 10.4 },
            fibraG: { type: "number", example: 2.4 },
            proteinasG: { type: "number", example: 0.3 },
            grasasG: { type: "number", example: 0.2 },
            vitaminaCMg: { type: "number", example: 4.6 },
            vitaminaAUg: { type: "number", example: 3 },
            vitaminaKUg: { type: "number", example: 2.2 },
            potasioMg: { type: "number", example: 107 },
            calcioMg: { type: "number", example: 6 },
            hierroMg: { type: "number", example: 0.12 },
            conservacionMetodo: { type: "string", example: "Refrigerada" },
            conservacionDuracionDias: { type: "integer", example: 30 },
            creadoEn: { type: "string", format: "date-time" },
            actualizadoEn: { type: "string", format: "date-time" },
          },
        },
        FrutaInput: {
          type: "object",
          required: ["nombre", "nombreCientifico", "descripcion", "categoria"],
          properties: {
            nombre: { type: "string", example: "Mango" },
            nombreCientifico: { type: "string", example: "Mangifera indica" },
            familiaBotanica: { type: "string", example: "Anacardiaceae" },
            otrosNombres: { type: "array", items: { type: "string" } },
            descripcion: { type: "string", example: "Fruta tropical dulce y jugosa" },
            categoria: { type: "string", example: "Drupa" },
            sabor: { type: "string", example: "Dulce e intenso" },
            origenPais: { type: "string", example: "India" },
            origenRegion: { type: "string", example: "Sur de Asia" },
            temporada: { type: "array", items: { type: "string" }, example: ["Primavera", "Verano"] },
            colores: { type: "array", items: { type: "string" }, example: ["Verde", "Amarillo", "Naranja"] },
            usosCulinarios: { type: "array", items: { type: "string" } },
            beneficios: { type: "array", items: { type: "string" } },
            alergias: { type: "array", items: { type: "string" } },
            curiosidades: { type: "array", items: { type: "string" } },
            imagenes: { type: "array", items: { type: "string" } },
            caloriasKcal: { type: "number", example: 60 },
            carbohidratosG: { type: "number", example: 15 },
            azucaresG: { type: "number", example: 13.7 },
            fibraG: { type: "number", example: 1.6 },
            proteinasG: { type: "number", example: 0.8 },
            grasasG: { type: "number", example: 0.4 },
            vitaminaCMg: { type: "number", example: 36.4 },
            vitaminaAUg: { type: "number", example: 54 },
            vitaminaKUg: { type: "number", example: 4.2 },
            potasioMg: { type: "number", example: 168 },
            calcioMg: { type: "number", example: 11 },
            hierroMg: { type: "number", example: 0.16 },
            conservacionMetodo: { type: "string" },
            conservacionDuracionDias: { type: "integer" },
          },
        },
        Paginacion: {
          type: "object",
          properties: {
            total: { type: "integer", example: 100 },
            pagina: { type: "integer", example: 1 },
            por_pagina: { type: "integer", example: 10 },
            total_paginas: { type: "integer", example: 10 },
          },
        },
        Error: {
          type: "object",
          properties: {
            error: { type: "string" },
          },
        },
        ErrorValidacion: {
          type: "object",
          properties: {
            error: { type: "string", example: "Error de validación" },
            detalles: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  campo: { type: "string" },
                  mensaje: { type: "string" },
                },
              },
            },
          },
        },
      },
    },
  },
  apis: ["./src/routes/*.ts"],
};

export default swaggerJsdoc(options);
